name: SheepPlugin
version: 1.0.0
main: com.drgnfireyellow.sheepplugin.sheepplugin
description: A plugin about sheep
author: DrgnFireYellow
website: https://github.com/DrgnFireYellow
api-version: '1.20'

commands:
  'sheep':
    description: 'Spawns a sheep'